### ISSUE TITLE
`loading` does not trigger again even if the `uri` changes.

### ISSUE THREAD

**Issue by IrvingArmenta** [CodeColde/use-fetch#1]
So I'm making an internal `blog` navigation using props from the `url` , I'm setting the fetch something 
```
const { postId } = props;
const uri = `https://jacklyons.me/wp-json/wp/v2/posts/${postId}?_embed_fields=content, title, date`;
const [loading, data] = useFetch(uri, {}, `post${postId}`, 'session');
```
So the fetch is working when they enter the first screen, and the `data` gets the proper data, the `loading` triggers with `true` and then `false` , as it should be, then, the data get stored, and that's alright. 

so then the user clicks in a `next post` button which is just pushing a history entry and changing the url which triggers a new `fetch` however, the `loading` prop coming from he `useFetch` hook does not change, it still throwing `false`, even though is a new `uri`. 

Also, the `data` object does not get "refreshed" on the `url` change, I know is using the `sessionStorage` at that time, and that's great, but I want to be able to get the `loading` prop to work as the first time and also `updating` the `data` prop coming from the fetch that matches the current `postId` .

I hope I'm making myself clear, I'm using `Preact 10` for this, which supports hooks fine, so that shouldn't be an issue I believe? 

the `data` coming from the `sessionStorage` should also match the current `postId`, right now it just stays the same, I'm trying to do something manual like:
```
const parsedData = JSON.parse(sessionStorage.getItem(`post${postId}`))
```
but I don't think that's the best approach, I believe everything should come properly from the `data` prop in the `hook`

**Comment by CodeColde** [comment]
Hi IrvingArmenta,

First of all, thank you for using my package. This is the first package I've released to the public that I felt could actually have a use case, so it means a lot to hear someone else out there is finding use in it :)

I have a feeling that your component isn't rerendering. Have you checked when your component is rerendering? And could you provide me with a codesandbox or something so I could check as well?

**Comment by IrvingArmenta** [comment]
Hello, 
I made this very `rough` example: https://codesandbox.io/s/pensive-einstein-e734t 

 My build is quite different though, I'm using Preact 10, and preact-router with an Async route, however, the problem is exactly the same, I hope it can make my `claim` clearer.

I'm not a `hooks expert` but if `postId` value changes, I think the re-rendering should happen, right? I added a useEffect() hook to check that.

**Comment by CodeColde** [comment]
Ah yes I came across this bug quite recently too. I've made an issue about it, and will pick it up soon. It's an issue with caching.

With version 0.1.0 the data does change but the loading state does not. I'll pick this up this week, and I should get it resolved. I'll keep you posted here for the release. Thanks for pointing it out

**Comment by CodeColde** [comment]
Hi,

Could you try upgrading the version of the package to 0.1.1? See if that resolves your problems?

**Comment by IrvingArmenta** [comment]
Hello,

the loading issue was fixed yes, however, I'd assume the `data` prop should have the current fetched data from storage, isn't that part of the functionality? 
so it should be something like: 

```
const key = `post${id}`;
if(sessionStorage.getItem(key)) { 
    const data = sessionStorage.getItem(key); 
    return data;
}
```
Hopefully it makes sense, I think it would be very convenient and it makes sense.

**Comment by CodeColde** [comment]
I believe it does. The first time it fetches, and if a type and key were provided it stores it in your chosen storage. the next time you fetch it it gets it directly from the storage. 

If there's something I'm missing feel free to ask.

**Comment by IrvingArmenta** [comment]
The `sessionStorage.getItem()` function does change, the data is already saved in the storage, therefore it works fine, what I'm talking about is the `data` prop coming from the hook. 
```
  const [loading, data] = useFetch(uri, {}, `post${postId}`, "session");
```
the `data` prop does not change again to the `1502` data even if I go back to the `/1502` url fetch. 
it's fine that `loading` is not triggered again, but the data form the `data` prop should change.

**Comment by CodeColde** [comment]
Hi Irving, you are correct, this is happening, and it shouldn't. I'm going to play around for a bit fix it. apologies for the delay.

**Comment by CodeColde** [comment]
Hi Irving, it should be fixed in the 0.1.3 version. I've got a test project you can look at as well!

**Comment by IrvingArmenta** [comment]
Hello again,

Great, I think this is the expected functionality 👍

**Comment by CodeColde** [comment]
Great to hear! Apologies for the delay! I'll close this issue :)
